In [ ]:
import pandas as pd
import numpy as np
data = open('txt_exo1.txt')

In [ ]:
liste = [line for line in data]
conso_adresses = [liste[i][:-1] for i in range(len(liste))]
d = {'conso_adresses': conso_adresses}
df = pd.DataFrame(data=d)
df

                     conso_adresses
0      96122 57 boulevard des Roses
1              14091 31 rue du Mont
2        39764 38 avenue de l'Arbre
3    72381 49 avenue de la Chapelle
4    3509 27 boulevard des Légendes
..                              ...
995    36417 19 avenue des Légendes
996  91630 37 boulevard du Ruisseau
997   15081 75 boulevard de Cristal
998    82612 37 avenue des Légendes
999   35161 30 chemin des Orchidées

[1000 rows x 1 columns]

In [ ]:
liste_conso = [int(df['conso_adresses'][i][0:df['conso_adresses'][i].index(' ')]) for i in range(1000)]
conso_max = max([int(df['conso_adresses'][i][0:df['conso_adresses'][i].index(' ')]) for i in range(1000)])
index_conso_max = liste_conso.index(conso_max)
df['conso_adresses'][index_conso_max]

'99979 52 chemin des Roses'